##### STATEFUL SET #####
deploymentKind: StatefulSet
appName: postgres
replicas: 1
appImage: postgres
appVersion: 15.1
imagePullPolicy: "IfNotPresent"
containerPort: 5432

containerEnvVars:
- name: POSTGRES_DB
  valueFromType: configMapKeyRef
  nameConfig: postgres-configmap
  keyConfig: POSTGRES_DB
- name: POSTGRES_USER
  valueFromType: configMapKeyRef
  nameConfig: postgres-configmap
  keyConfig: POSTGRES_USER
- name: POSTGRES_PASSWORD
  valueFromType: secretKeyRef
  nameConfig: postgres-secret
  keyConfig: POSTGRES_PASSWORD

StatefulSet: 1
volumeName: postgresdb
mountPath: /var/lib/postgresql/data
volumeSize: 5Gi
subPath: postgres

##### SERVICE #####
serviceName: postgres-service
serviceType: ClusterIP
servicePort: 5432
serviceProtocol: TCP

##### CONFIG MAP #####
configName: postgres-configmap
configMapVars:
- name: POSTGRES_DB
  value: posts
- name: POSTGRES_USER
  value: postgres

##### SECRET #####
secretName: postgres-secret
secretVars:
- name: POSTGRES_PASSWORD
  value: defaultpwd

